version: "3"
services:
  data-jog-app:
     build: .
     ports:
        - "7000:${PORT}"
     volumes:
        - ./:/app:ro
        - /app/node_modules
     environment:
        - PORT=${PORT}
        





