version: "3"
services:
  nginx:
      image: nginx:stable-alpine
      volumes:
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  data-jog-app:
     build: .
     expose:
        - "3000"
     environment:
        - PORT=3000
  mongo: 
      image: mongo
      volumes:
         - mongo-db:/data/db
  redis:
      image: redis

volumes:
   mongo-db:
