version: "3"
services:
   nginx:
      ports:
         - "3000:80"
   data-jog-app:
      build:
         context: .
         args:
            NODE_ENV: development
      volumes:
        - ./:/app:ro
        - /app/node_modules
      environment:
        - NODE_ENV=development
        - MONGO_USER=mongoUser
        - MONGO_PASS=mongoPass
        - REDIS_SECRET=keyboard-cat
      command: npm run dev

   mongo: 
      environment:
         MONGO_INITDB_ROOT_USERNAME: mongoUser
         MONGO_INITDB_ROOT_PASSWORD: mongoPass


