version: "3"
services:
  data-jog-app:
     build:
      context: .
      args:
         NODE_ENV: production
     environment:
        - NODE_ENV=production
     command: node server.js
  nginx:
     ports:
      - "80:80"